import type { Metadata } from "next";
import Script from "next/script";
import { EB_Garamond, Manrope } from "next/font/google";
import { Language } from "@/Types/Language.ts";
import "@/Styles/globals.scss";
import { Header } from "@/Components/Common/Header/Header.tsx";
import { Footer } from "@/Components/Common/Footer/Footer.tsx";
import { ChatBotWidget } from "@/Components/Common/ChatBotWidget/ChatBotWidget.tsx";
import { CookieConsent } from "@/Components/Common/CookieConsent/CookieConsent.tsx";
import { LanguageProvider } from "@/Context/LanguageContext.tsx";
import { NavigationProvider } from "@/Context/NavigationContext.tsx";

const ebgaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin", 'cyrillic'],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", 'cyrillic'],
});

export const metadata: Metadata = {
  title: "Hashtag Innovations",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
  params,

}: Readonly<{
  children: React.ReactNode,
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const currentLang = lang as Language;
  return (
    <html lang={lang} className={`${ebgaramond.variable} ${manrope.variable}`}>
      <body>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-SR64MPBLXQ"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            const analyticsConsent = window.localStorage.getItem('hashtag_cookie_consent') === 'accepted' ? 'granted' : 'denied';
            gtag('consent', 'default', {
              analytics_storage: analyticsConsent,
            });
            gtag('js', new Date());
            gtag('config', 'G-SR64MPBLXQ');
          `}
        </Script>
        <LanguageProvider initialLang={currentLang}>
          <NavigationProvider>
            <Header lang={lang} />
            <main className="main-container">
              {children}
            </main>
            <Footer lang={lang} />
            <ChatBotWidget />
            <CookieConsent />
          </NavigationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
