import type { Metadata } from "next";
import { EB_Garamond, Manrope } from "next/font/google";
import { Language } from "@/Types/Language.ts";
import "@/Styles/globals.scss";
import { Header } from "@/Components/Common/Header/Header.tsx";
import { Footer } from "@/Components/Common/Footer/Footer.tsx";
import { LanguageProvider } from "@/Context/LanguageContext.tsx";
import { NavigationProvider } from "@/Context/NavigationContext.tsx";

const ebgaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin", 'cyrillic'],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", 'cyrillic'],
});

export const metadata: Metadata = {
  title: "Hashtag Innovations",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,

}: Readonly<{
  children: React.ReactNode,
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const currentLang = lang as Language;
  return (
    <html lang={lang} className={`${ebgaramond.variable} ${manrope.variable}`}>
      <body>
        <LanguageProvider initialLang={currentLang}>
          <NavigationProvider>
            <Header lang={lang} />
            <main className="main-container">
              {children}
            </main>
            <Footer lang={lang} />
          </NavigationProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}

