import type { Metadata } from "next";
import { EB_Garamond, Manrope } from "next/font/google";
import { i18n } from "../Lib/i18n";
import { Language } from "@/Types/Language";


const ebgaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin", 'cyrillic'],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", 'cyrillic'],
});

export const metadata: Metadata = {
  title: "Hashtag Innovations",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,

}: Readonly<{
  children: React.ReactNode,
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const currentLang = lang as Language;
  return (
    <html lang={lang} className={`${ebgaramond.variable} ${manrope.variable}`}>
      <body>{children}</body>
    </html>
  );
}
