export const MOCK_TEXTBOOKS_EN = [
  {
    id: "material-innovation-outlook",
    title: "Innovation Outlook 2026",
    excerpt: "Key trends, data, and practical frameworks shaping the future of business innovation across fast-moving markets.",
    authorLabel: "Author:",
    authorName: "Andrew Nikolov",
    authorExpertId: "expert-1",
    imageUrl: "/images/community/summit_event.png",
    pdfUrl: "/en/learn?material=innovation-outlook",
    previewPdfUrl: "/test.pdf",
    salesUrl: "/en/learn?material=innovation-outlook",
    category: "Innovation",
    format: "PDF",
    price: "€20",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-01-16T10:00:00Z",
  },
  {
    id: "material-ai-product-playbook",
    title: "AI Product Strategy Playbook",
    excerpt: "A field guide for teams building AI-enabled products, from opportunity mapping to responsible launch plans.",
    authorLabel: "Author:",
    authorName: "Maya Petrova",
    authorExpertId: "expert-2",
    imageUrl: "/images/community/ai_event.png",
    pdfUrl: "/en/learn?material=ai-product-playbook",
    salesUrl: "/en/learn?material=ai-product-playbook",
    category: "AI",
    format: "Guide",
    price: "€35",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-02-08T10:00:00Z",
  },
  {
    id: "material-fintech-models",
    title: "Fintech Business Models",
    excerpt: "Understand the revenue models, compliance patterns, and customer journeys that drive modern finance platforms.",
    authorLabel: "Author:",
    authorName: "Michael Chen",
    authorExpertId: "expert-3",
    imageUrl: "/images/community/finance_event.png",
    pdfUrl: "/en/learn?material=fintech-models",
    salesUrl: "/en/learn?material=fintech-models",
    category: "Business",
    format: "Report",
    price: "€28",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "material-founder-sales",
    title: "Founder Sales System",
    excerpt: "A practical workbook for positioning, outreach, discovery calls, and follow-up sequences for early-stage founders.",
    authorLabel: "Author:",
    authorName: "Elena Georgieva",
    authorExpertId: "expert-4",
    imageUrl: "/images/platform/slide_connect.png",
    pdfUrl: "/en/learn?material=founder-sales",
    salesUrl: "/en/learn?material=founder-sales",
    category: "Business",
    format: "Workbook",
    price: "€18",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-03-02T10:00:00Z",
  },
  {
    id: "material-tech-leadership",
    title: "Technology Leadership Toolkit",
    excerpt: "Templates and principles for leading engineering teams, prioritizing roadmaps, and communicating technical risk.",
    authorLabel: "Author:",
    authorName: "David Kim",
    authorExpertId: "expert-1",
    imageUrl: "/images/community/tech_event.png",
    pdfUrl: "/en/learn?material=tech-leadership",
    salesUrl: "/en/learn?material=tech-leadership",
    category: "Technology",
    format: "Toolkit",
    price: "€32",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "material-market-entry",
    title: "Bulgaria Market Entry Notes",
    excerpt: "A concise guide to market research, local partnerships, pricing validation, and first customer acquisition.",
    authorLabel: "Author:",
    authorName: "Jane Smith",
    imageUrl: "/images/platform/slide_jobs.png",
    pdfUrl: "/en/learn?material=market-entry",
    salesUrl: "/en/learn?material=market-entry",
    category: "Business",
    format: "Notes",
    price: "€15",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-03-21T10:00:00Z",
  },
  {
    id: "material-design-systems",
    title: "Design Systems for Scale",
    excerpt: "Learn how to define tokens, document components, and align product teams around reusable interface patterns.",
    authorLabel: "Author:",
    authorName: "Sarah Ivanova",
    imageUrl: "/images/platform/slide_skills.png",
    pdfUrl: "/en/learn?material=design-systems",
    salesUrl: "/en/learn?material=design-systems",
    category: "Technology",
    format: "Guide",
    price: "€24",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-04-04T10:00:00Z",
  },
  {
    id: "material-cybersecurity-basics",
    title: "Cybersecurity Basics for Teams",
    excerpt: "Protect web products against common vulnerabilities and build practical security habits inside product teams.",
    authorLabel: "Author:",
    authorName: "Bob Brown",
    imageUrl: "/images/default_textbook_cover.png",
    pdfUrl: "/en/learn?material=cybersecurity-basics",
    salesUrl: "/en/learn?material=cybersecurity-basics",
    category: "Technology",
    format: "Checklist",
    price: "€12",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-04-12T10:00:00Z",
  },
  {
    id: "material-community-growth",
    title: "Community Growth Manual",
    excerpt: "A structured manual for building expert communities, running member rituals, and measuring engagement.",
    authorLabel: "Author:",
    authorName: "Andrew Nikolov",
    authorExpertId: "expert-1",
    imageUrl: "/images/platform/slide_events.png",
    pdfUrl: "/en/learn?material=community-growth",
    salesUrl: "/en/learn?material=community-growth",
    category: "Innovation",
    format: "Manual",
    price: "€22",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-04-24T10:00:00Z",
  },
];

export const MOCK_TEXTBOOKS_BG = [
  {
    id: "material-innovation-outlook",
    title: "Прогноза за иновациите 2026",
    excerpt: "Ключови тенденции, данни и практически модели, които оформят бъдещето на бизнес иновациите.",
    authorLabel: "Автор:",
    authorName: "Андрей Николов",
    authorExpertId: "expert-1",
    imageUrl: "/images/community/summit_event.png",
    pdfUrl: "/bg/learn?material=innovation-outlook",
    previewPdfUrl: "/test.pdf",
    salesUrl: "/bg/learn?material=innovation-outlook",
    category: "Иновации",
    format: "PDF",
    price: "€20",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-01-16T10:00:00Z",
  },
  {
    id: "material-ai-product-playbook",
    title: "AI продуктова стратегия",
    excerpt: "Практическо ръководство за екипи, които създават AI продукти - от идея до отговорно пускане.",
    authorLabel: "Автор:",
    authorName: "Мая Петрова",
    authorExpertId: "expert-2",
    imageUrl: "/images/community/ai_event.png",
    pdfUrl: "/bg/learn?material=ai-product-playbook",
    salesUrl: "/bg/learn?material=ai-product-playbook",
    category: "Изкуствен интелект",
    format: "Ръководство",
    price: "€35",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-02-08T10:00:00Z",
  },
  {
    id: "material-fintech-models",
    title: "Финтех бизнес модели",
    excerpt: "Разберете приходните модели, регулаторните рамки и клиентските пътеки във финансовите платформи.",
    authorLabel: "Автор:",
    authorName: "Майкъл Чен",
    authorExpertId: "expert-3",
    imageUrl: "/images/community/finance_event.png",
    pdfUrl: "/bg/learn?material=fintech-models",
    salesUrl: "/bg/learn?material=fintech-models",
    category: "Бизнес",
    format: "Доклад",
    price: "€28",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "material-founder-sales",
    title: "Система за основателски продажби",
    excerpt: "Работна тетрадка за позициониране, контакт с клиенти, discovery разговори и последваща комуникация.",
    authorLabel: "Автор:",
    authorName: "Елена Георгиева",
    authorExpertId: "expert-4",
    imageUrl: "/images/platform/slide_connect.png",
    pdfUrl: "/bg/learn?material=founder-sales",
    salesUrl: "/bg/learn?material=founder-sales",
    category: "Бизнес",
    format: "Работна тетрадка",
    price: "€18",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-03-02T10:00:00Z",
  },
  {
    id: "material-tech-leadership",
    title: "Инструменти за технологично лидерство",
    excerpt: "Шаблони и принципи за водене на инженерни екипи, пътни карти и комуникация на технически риск.",
    authorLabel: "Автор:",
    authorName: "Дейвид Ким",
    authorExpertId: "expert-1",
    imageUrl: "/images/community/tech_event.png",
    pdfUrl: "/bg/learn?material=tech-leadership",
    salesUrl: "/bg/learn?material=tech-leadership",
    category: "Технологии",
    format: "Инструментариум",
    price: "€32",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "material-market-entry",
    title: "Бележки за навлизане на българския пазар",
    excerpt: "Кратко ръководство за пазарно проучване, партньорства, валидиране на цени и първи клиенти.",
    authorLabel: "Автор:",
    authorName: "Джейн Смит",
    imageUrl: "/images/platform/slide_jobs.png",
    pdfUrl: "/bg/learn?material=market-entry",
    salesUrl: "/bg/learn?material=market-entry",
    category: "Бизнес",
    format: "Бележки",
    price: "€15",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-03-21T10:00:00Z",
  },
  {
    id: "material-design-systems",
    title: "Дизайн системи за мащаб",
    excerpt: "Научете как да дефинирате токени, документирате компоненти и синхронизирате продуктови екипи.",
    authorLabel: "Автор:",
    authorName: "Сара Иванова",
    imageUrl: "/images/platform/slide_skills.png",
    pdfUrl: "/bg/learn?material=design-systems",
    salesUrl: "/bg/learn?material=design-systems",
    category: "Технологии",
    format: "Ръководство",
    price: "€24",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-04-04T10:00:00Z",
  },
  {
    id: "material-cybersecurity-basics",
    title: "Основи на киберсигурността за екипи",
    excerpt: "Защитете уеб продукти от чести уязвимости и изградете практически навици за сигурност.",
    authorLabel: "Автор:",
    authorName: "Боб Браун",
    imageUrl: "/images/default_textbook_cover.png",
    pdfUrl: "/bg/learn?material=cybersecurity-basics",
    salesUrl: "/bg/learn?material=cybersecurity-basics",
    category: "Технологии",
    format: "Чеклист",
    price: "€12",
    badge: "PDF",
    hasPreview: true,
    isTrending: false,
    createdAt: "2026-04-12T10:00:00Z",
  },
  {
    id: "material-community-growth",
    title: "Наръчник за растеж на общност",
    excerpt: "Структуриран наръчник за експертни общности, ритуали за членове и измерване на ангажираността.",
    authorLabel: "Автор:",
    authorName: "Андрей Николов",
    authorExpertId: "expert-1",
    imageUrl: "/images/platform/slide_events.png",
    pdfUrl: "/bg/learn?material=community-growth",
    salesUrl: "/bg/learn?material=community-growth",
    category: "Иновации",
    format: "Наръчник",
    price: "€22",
    badge: "PDF",
    hasPreview: true,
    isTrending: true,
    createdAt: "2026-04-24T10:00:00Z",
  },
];
