# Generated by Django 5.2.15 on 2026-07-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='show_dot',
        ),
    ]
