# Generated by Django 5.2.15 on 2026-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_tag_show_dot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
