# Generated by Django 5.2.15 on 2026-07-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='external_url',
        ),
    ]
