# Generated by Django 5.2.16 on 2026-08-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_aftersalesservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsightSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(blank=True)),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('workday_start', models.TimeField(default='09:00')),
                ('workday_end', models.TimeField(default='18:00')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insight_settings', to='content.expert')),
            ],
            options={
                'verbose_name': 'AI insight settings',
                'verbose_name_plural': 'AI insight settings',
            },
        ),
    ]
