# Generated by Django 5.2.16 on 2026-08-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_aiinsightsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsightsettings',
            name='workday_end',
        ),
        migrations.RemoveField(
            model_name='aiinsightsettings',
            name='workday_start',
        ),
    ]
