# Generated by Django 5.2.16 on 2026-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_remove_aiinsightsettings_workday_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsightsettings',
            name='generation_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsightsettings',
            name='generation_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiinsightsettings',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsightsettings',
            name='generation_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=16),
        ),
    ]
